### PR TITLE
Idiomatic Hana way to write unify

### PR DESCRIPTION
**Pull request by ldionne**
The first commit uses https instead of the git protocol to fetch the Hana submodule. Otherwise GitHub would complain about me not having the proper private key or something.

The second commit reimplements the `unify` function in a more Hana way. I'm aware that you were probably going to add more complexity to this whole `unify` function and my naive implementation may not be flexible enough for what you need. I'll help you sort it out when I understand what is actually this `unify` thing. Looking at Wikipedia unfortunately leaves me with only a vague idea.

The third commit makes sure we're using the latest version of Hana. The version on the redux branch is a bit outdated (Hana moves fast), and it does not work with GCC yet anyway. Hana's master currently works with Clang 3.5 and contains several improvements.

### CODE REVIEW

**Comment by ldionne** [comment]
As for the ambiguous overloads you were getting in your initial implementation, I'm not sure why this was happening, frankly. I'll try to find out.

**Comment by ldionne** [comment]
Ok, I narrowed down the problem with you previous `unify` to a minimal example that does not use Hana at all. So the problem is not in Hana, phew :-)

```cpp
template <typename ...>
struct _tuple { };

template <typename LT, typename RT>
void unify(LT lhs, RT rhs) { }

template <typename HL, typename HR>
void unify(_tuple<HL> lhs, _tuple<HR> rhs) { }

template <typename HL, typename ...TL, typename HR, typename ...TR>
void unify(_tuple<HL, TL...> lhs, _tuple<HR, TR...> rhs) { }

int main() {
    _tuple<char> xs;
    unify(xs, xs);
}
```

**Comment by brunocodutra** [comment]
The way you implemented unify does solve the basic example I initially proposed, but it is sadly not flexible enough. In very few words, unification is the algorithm such that given two expressions \<a\> and \<b\> it returns *true* if and only if there exists a set of *unifiers* which make them *identical*. Consider the following examples, where lower case letters are constants, upper case letters are variables and angle brackets denote tuples.

1.  unify(\<a\> \<a\>) -> {true, {}}
2.  unify(\<a, a\> \<a, b\>) -> {false, {}}
3.  unify(\<a, X\> \<a, b\>) -> {true, {X -> b}}
4.  unify(\<X, X\> \<a, b\>) -> {false, {}}
5.  unify(\<X, \<\<a\>, Y\>\>, \<\<Y\>, \<X, a\>\>) -> {true, {X -> \<a\>, Y -> a}}

Now regarding the ambiguity issue, is in fact due to a language feature. Considering your simple example, after template argument deduction, the compiler is left with 3 *function overloads* of identical signature, hence the ambiguity.

``` c++
void unify(_tuple<char> lhs, _tuple<char> rhs) { } //LT and RT resolved to _tuple<char>
void unify(_tuple<char> lhs, _tuple<char> rhs) { } //HL and HR resolved to char
void unify(_tuple<char> lhs, _tuple<char> rhs) { } //HL and HR resolved to char
                                                   //TL and RT resolved to an empty pack
```
This is not an issue when one deals solely with metafunctions as defined by MPL, for there's no such thing as *type overloading*, the compiler simply chooses the candidate whose template deduction is *closest* (lets not go into details here) to the actual arguments.

The only way I saw around this it was to rely on SFINAE, but I couldn't find any concept introspection for Hana sequences. Now I think this is what I've been looking for:

``` c++
hana::models<hana::Sequence, hana::datatype_t<T>>{};
```

**Comment by brunocodutra** [comment]
I've actually managed to avoid the ambiguity by allowing empty tuples as valid unifiable expressions, didn't even have to rely on SFINAE for now. To be honest, these template deduction/overload selection rules drive me nuts, it invariably leads to trial and error at some point. 

Btw, thank you for pointing me out that https would be better suited for read only submodules and that Hana's master branch now compiles on clang 3.5.2+. In fact, I managed to run hanalog so far even on clang 3.5.1.

**Comment by ldionne** [comment]
I'm currently trying to make it work on Clang 3.5.0 on Travis CI; and so far it looks relatively good.

**Pull request closed without merging**
